name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2.3.1
      - name: Install and Build 
        run: |
          yarn install
          yarn build 
        env:
          REACT_APP_DATA_REPO: ${{ secrets.REACT_APP_DATA_REPO }}
      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages 
          folder: build 
          token: ${{ secrets.GH_TOKEN }}